spring:
  application:
    name: HOTEL-BOOK-SERVICE

server:
  port: 8087
  servlet:
    context-path: "/hotel-book-service"

info:
  app:
    name: '@project.name@'
    version: '@project.version@'


management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /monitoring

supplier:
  endPoint:
    url: "https://traveldoo.koedia.com"

grpc:
  client:
    hotel-book-reprice-pad:
      address: 'discovery:///hotel-book-reprice-pad'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

eureka:
  instance:
    prefer-ip-address: true
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${eureka.service-url.default}

