---
apiVersion: v1
kind: Service
metadata:
  name: hotel-book-service
  namespace: beta-app
spec:
  type: ClusterIP
  ports:
    - port: 8087
      targetPort: 8087
  selector:
    app.kubernetes.io/name: hotel-book-service